#I learned about how variables require placeholders before insirting your information
#I also learned how [print ()] allows for a block of space inbetween text
print()
print("Getting to know you!")
print()
myName = input("What is your name?")
myFood = input("What is your favorite food?")
myMusic = input("What is your favorite music?")
myPlace = input("Where do you live?")
print()
print("You're name is")  
print(myName)
print ()
print("You are craving")
print(myFood)
print("and you're definitely listening to")
print(myMusic)
print("living at")
print(myPlace)
print ()
print ("guess what? you won't fail school!")
